// ── ClickUp Integration ────────────────────────────────────────────────────
// Auto-creates editor cards in a client's ClickUp list when they approve
// a script in the portal. The agency uses ONE shared API token (env var
// CLICKUP_API_TOKEN) — every client's folder lives in the same workspace.
// Per-client config in configs.clickupListId points at the target list.
// Each script remembers its task id (clickupCardId) so we update on
// re-approval instead of duplicating.
//
// API docs: https://clickup.com/api
// Token type: Personal API Key (starts with "pk_"). Generated by the agency
// owner in ClickUp → Settings → Apps → API Token.

import type { Script, Config } from "./types";

const CLICKUP_API = "https://api.clickup.com/api/v2";

function getToken(): string {
  const t = (process.env.CLICKUP_API_TOKEN || "").trim();
  if (!t) throw new Error("CLICKUP_API_TOKEN env var not set");
  return t;
}

interface ClickUpTaskResponse {
  id: string;
  name?: string;
  url?: string;
  [k: string]: unknown;
}

interface ClickUpError {
  err?: string;
  ECODE?: string;
}

/** Build the markdown body for a ClickUp card from a script + client info.
 *  Editor reads this to know exactly what to film/edit. */
export function buildCardDescription(script: Script, clientName?: string): string {
  const parts: string[] = [];

  if (clientName) parts.push(`**Client:** ${clientName}`);
  if (script.format) parts.push(`**Format:** ${script.format}`);
  if (script.pillar) parts.push(`**Pillar:** ${script.pillar}`);
  if (script.contentType) parts.push(`**Content-Type:** ${script.contentType}`);
  parts.push("");

  if (script.textHook) {
    parts.push(`### Text-Hook (On-Screen)`);
    parts.push(script.textHook);
    parts.push("");
  }
  if (script.visualHook) {
    parts.push(`### Visual-Hook`);
    parts.push(script.visualHook);
    parts.push("");
  }
  if (script.hook) {
    parts.push(`### Audio-Hook (gesprochen)`);
    parts.push(script.hook);
    parts.push("");
  }

  if (script.body) {
    parts.push(`### Skript`);
    parts.push(script.body);
    parts.push("");
  }
  if (script.cta) {
    parts.push(`### CTA`);
    parts.push(script.cta);
    parts.push("");
  }

  if (script.bRoll) {
    parts.push(`### B-Roll`);
    parts.push(script.bRoll);
    parts.push("");
  }
  if (script.shotList) {
    parts.push(`### Shot-List / Filmanweisungen`);
    parts.push(script.shotList);
    parts.push("");
  }
  if (script.caption) {
    parts.push(`### Videobeschreibung (Caption)`);
    parts.push(script.caption);
    parts.push("");
  }

  if (script.clientFeedbackText) {
    parts.push(`### Kunden-Feedback`);
    parts.push(script.clientFeedbackText);
    parts.push("");
  }

  return parts.join("\n").trim();
}

/** POST a new task to ClickUp. Returns the created task id. */
async function createTask(
  token: string,
  listId: string,
  payload: { name: string; description: string },
): Promise<string> {
  const res = await fetch(`${CLICKUP_API}/list/${listId}/task`, {
    method: "POST",
    headers: { Authorization: token, "Content-Type": "application/json" },
    body: JSON.stringify({
      name: payload.name,
      markdown_description: payload.description,
      // Could add: tags, priority, assignees, due_date later.
    }),
  });
  if (!res.ok) {
    const errBody = (await res.json().catch(() => ({}))) as ClickUpError;
    throw new Error(`ClickUp create failed (${res.status}): ${errBody.err || errBody.ECODE || "unknown"}`);
  }
  const data = (await res.json()) as ClickUpTaskResponse;
  if (!data.id) throw new Error("ClickUp create returned no task id");
  return data.id;
}

/** PUT an existing task — updates name + description. */
async function updateTask(
  token: string,
  taskId: string,
  payload: { name: string; description: string },
): Promise<void> {
  const res = await fetch(`${CLICKUP_API}/task/${taskId}`, {
    method: "PUT",
    headers: { Authorization: token, "Content-Type": "application/json" },
    body: JSON.stringify({
      name: payload.name,
      markdown_description: payload.description,
    }),
  });
  if (!res.ok) {
    const errBody = (await res.json().catch(() => ({}))) as ClickUpError;
    throw new Error(`ClickUp update failed (${res.status}): ${errBody.err || errBody.ECODE || "unknown"}`);
  }
}

/** Idempotent upsert: create-if-new, update-if-existing. Returns the
 *  resulting task id (same as input cardId on update path). */
export async function upsertScriptCard(args: {
  config: Pick<Config, "clickupListId" | "name" | "configName">;
  script: Script;
}): Promise<{ taskId: string; created: boolean }> {
  const token = getToken();
  const listId = (args.config.clickupListId || "").trim();
  if (!listId) throw new Error("ClickUp List ID not configured for this client");

  const description = buildCardDescription(
    args.script,
    args.config.name || args.config.configName || undefined,
  );
  const name = args.script.title || "Skript ohne Titel";

  if (args.script.clickupCardId) {
    // Existing card → update
    try {
      await updateTask(token, args.script.clickupCardId, { name, description });
      return { taskId: args.script.clickupCardId, created: false };
    } catch (err) {
      // If the task was deleted in ClickUp, fall through to create a new one.
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes("404") && !msg.toLowerCase().includes("not found")) throw err;
    }
  }

  const taskId = await createTask(token, listId, { name, description });
  return { taskId, created: true };
}

/** Quick connectivity test from the admin "ClickUp verbinden" UI.
 *  Calls GET /list/{id} which returns the list metadata if both the
 *  agency-wide token (env) and the list id are valid. */
export async function testConnection(listId: string): Promise<{
  ok: boolean;
  listName?: string;
  error?: string;
}> {
  let token: string;
  try {
    token = getToken();
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
  try {
    const res = await fetch(`${CLICKUP_API}/list/${listId.trim()}`, {
      headers: { Authorization: token },
    });
    if (!res.ok) {
      const errBody = (await res.json().catch(() => ({}))) as ClickUpError;
      return { ok: false, error: errBody.err || errBody.ECODE || `HTTP ${res.status}` };
    }
    const data = (await res.json()) as { name?: string };
    return { ok: true, listName: data.name };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

// ── List Browser ────────────────────────────────────────────────────────────
// Walks the workspace tree (teams → spaces → folders → lists) so the admin
// can pick a list from a dropdown instead of hunting for the numeric id in
// ClickUp's URL bar. Done in parallel per-space.

interface CUTeam { id: string; name: string }
interface CUSpace { id: string; name: string }
interface CUFolder { id: string; name: string; lists?: CUList[] }
interface CUList { id: string; name: string }

export interface FlatList {
  id: string;
  name: string;
  path: string;        // "Space › Folder › List" or "Space › List" for folderless
  spaceName: string;
  folderName?: string;
}

async function cuFetch<T>(token: string, path: string): Promise<T> {
  const res = await fetch(`${CLICKUP_API}${path}`, { headers: { Authorization: token } });
  if (!res.ok) {
    const errBody = (await res.json().catch(() => ({}))) as ClickUpError;
    throw new Error(errBody.err || errBody.ECODE || `HTTP ${res.status} on ${path}`);
  }
  return res.json() as Promise<T>;
}

/** Returns every list the agency token has access to, flattened with
 *  human-readable paths so the UI can show them in a dropdown. */
export async function listAllLists(): Promise<{ ok: boolean; lists?: FlatList[]; error?: string }> {
  let token: string;
  try {
    token = getToken();
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }

  try {
    const teamsRes = await cuFetch<{ teams: CUTeam[] }>(token, "/team");
    const teams = teamsRes.teams || [];
    const out: FlatList[] = [];

    for (const team of teams) {
      const spacesRes = await cuFetch<{ spaces: CUSpace[] }>(token, `/team/${team.id}/space?archived=false`);
      const spaces = spacesRes.spaces || [];

      // Per-space: fetch folders+lists and folderless lists in parallel.
      await Promise.all(spaces.map(async (space) => {
        const [foldersRes, looseRes] = await Promise.all([
          cuFetch<{ folders: CUFolder[] }>(token, `/space/${space.id}/folder?archived=false`).catch(() => ({ folders: [] })),
          cuFetch<{ lists: CUList[] }>(token, `/space/${space.id}/list?archived=false`).catch(() => ({ lists: [] })),
        ]);

        for (const folder of foldersRes.folders || []) {
          for (const list of folder.lists || []) {
            out.push({
              id: list.id,
              name: list.name,
              path: `${space.name} › ${folder.name} › ${list.name}`,
              spaceName: space.name,
              folderName: folder.name,
            });
          }
        }
        for (const list of looseRes.lists || []) {
          out.push({
            id: list.id,
            name: list.name,
            path: `${space.name} › ${list.name}`,
            spaceName: space.name,
          });
        }
      }));
    }

    out.sort((a, b) => a.path.localeCompare(b.path));
    return { ok: true, lists: out };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}
